# Generated by Django 5.1.3 on 2024-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
