# Generated by Django 5.1.3 on 2024-12-03 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_accommodation_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='localizeaccommodation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='localizeaccommodation',
            unique_together=set(),
        ),
    ]
